### PR TITLE
correct the link target to omit bin

### PR DESCRIPTION
**Pull request by cabrinha**
The jar file doesn't seem to have "bin" in the name when it gets created.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Thanks for the patch @cabrinha. Did you run the acceptance tests locally?

**Comment by cabrinha** [comment]
> Thanks for the patch @cabrinha. Did you run the acceptance tests locally?

I did not. Whats the process for that?

**Comment by bastelfreak** [comment]
@cabrinha I added support to acceptane tests to your branch. Please do a `git pull` before committing new changes. You can click on the travis link to view the failed acceptance tests. If you want to run the tests locally you need a docker daemon installed, the dependencies from our gemfile and afterwards execute beaker to kick off the tests. For example:

```
PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker bundle exec rake beaker
```

**Comment by cabrinha** [comment]
After a little more testing, I've found any version 5.x.x is going to have `-bin` appended to the name of the jar file and any version 8.x.x will not.

I'm not sure I want to proceed with this PR at the moment. I'll just carry on creating the link outside of the module.

**Pull request closed without merging**
